

function Maingrid() {
  return (
    <div className='grid grid-cols-11 gap-2 p-4 ml-0 mr-0 md:mx-60 2xl:mx-96 bg-black text-white text-xs pb-36'>
      <div className='fa-solid fa-football text-xl'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>0</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>1</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>2</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>3</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>4</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>5</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>6</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>7</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>8</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>9</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>0</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-blue-500 text-center'>CN</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-red-500 text-center '>KN</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>1</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-red-500 text-center'>KN</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>2</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-blue-500 text-center'>WW</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>3</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-blue-500 text-center'>CN</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>4</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-blue-500 text-center'>CN</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>5</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-blue-500 text-center'>WW</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>6</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>7</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-red-500 text-center'>KN</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>8</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pl-2 font-bold shadow-md shadow-green-500 text-base'>9</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-blue-500 text-center'>WW</div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      <div className='border border-white h-7 w-7 md:w-14 md:h-14 pt-1 font-bold shadow-md shadow-white text-center'></div>
      
    </div>
  )
}

export default Maingrid
